<?php
if ($_SERVER['REQUEST_METHOD'] === 'POST') {
    $url = $_POST['url'];

    // Call the Node.js script to scrape reviews
    $command = "node scrape_reviews.js " . escapeshellarg($url);
    $output = shell_exec($command);

    // Read the reviews from the JSON file generated by Puppeteer
    $reviews = json_decode(file_get_contents('reviews.json'), true);

    if ($reviews) {
        echo "<h1>Customer Reviews</h1>";
        echo "<div class='reviews-container'>";
        foreach ($reviews as $review) {
            echo "<div class='review-item'>";
            echo "<h3>" . htmlspecialchars($review['reviewerName']) . "</h3>";
            echo "<div class='rating'>" . htmlspecialchars($review['rating']) . " Stars</div>";
            echo "<p>" . htmlspecialchars($review['reviewText']) . "</p>";
            echo "</div>";
        }
        echo "</div>";
    } else {
        echo "<p>No reviews found for this URL.</p>";
    }
} else {
    echo "<p>Please submit a URL to scrape reviews.</p>";
}
?>



<style>
    .reviews-container {
        width: 80%;
        margin: auto;
    }
    .review-item {
        border: 1px solid #ddd;
        padding: 15px;
        margin-bottom: 20px;
        border-radius: 5px;
        background-color: #f9f9f9;
    }
    .review-item h3 {
        margin: 0;
        color: #333;
    }
    .rating {
        font-weight: bold;
        color: #f39c12;
    }
    .review-item p {
        font-size: 16px;
        color: #555;
    }
</style>
